# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e88d5efdb438c5baced7a7d30acd089eac9e757c6894ddf75c30136aa0cd8e72050ba26349c3539a7b539eb9e1ee14bf228427e714eea754d0e12eb49f93ef1

test:
  secret_key_base: 2a01efd45c6ca1df358560723110fb561efa6502be5d567986cfcdadbdd78b64706989535cf023474483ff16a838945564189bca29f7ef68e59d34fdf8baeb99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
